### ISSUE TITLE
2.0.4 not handling 0 byte files

### ISSUE THREAD

**Issue by danielkasen** [cherweg/logstash-input-s3-sns-sqs#28]
Looks like there's a breaking change in 2.0.4 where downloading and processing a 0 byte file throws an error and causies the pipeline to crash with this error:

`[Worker s3_rds_0/0] Incomplete message in read_file. We´ll throw skip_delete.`

> /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-2.0.4/lib/logstash/inputs/sqs/poller.rb:126:in` `block in run', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413:in `block in yield_messages', org/jruby/RubyArray.java:1734:in `each', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `yield_messages', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `block in process_messages', org/jruby/RubyKernel.java:1114:in `catch', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `block in poll', org/jruby/RubyKernel.java:1292:in `loop', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll', org/jruby/RubyKernel.java:1114:in `catch', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/aws-sdk-resources-2.11.177/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-2.0.4/lib/logstash/inputs/sqs/poller.rb:82:in `block in run', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-2.0.4/lib/logstash/inputs/sqs/poller.rb:176:in `run_with_backoff', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-2.0.4/lib/logstash/inputs/sqs/poller.rb:80:in `run', /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-2.0.4/lib/logstash/inputs/s3snssqs.rb:320:in `block in run_worker_thread'

**Comment by danielkasen** [comment]
Add this output too 
`File too small to calculate signature`
