### ISSUE TITLE
error on test execution

### ISSUE THREAD

**Issue by zeph** [cherweg/logstash-input-s3-sns-sqs#43]
```
/home/gms/.rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:476: warning: constant ::Fixnum is deprecated
/home/gms/.rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:480: warning: constant ::Fixnum is deprecated
/home/gms/.rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:503: warning: constant ::Fixnum is deprecated
/home/gms/.rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:507: warning: constant ::Fixnum is deprecated
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.9.1 - omit version 2.9.7
--- jar coordinate com.fasterxml.jackson.module:jackson-module-afterburner already loaded with version 2.9.1 - omit version 2.9.7
--- jar coordinate com.fasterxml.jackson.core:jackson-core already loaded with version 2.9.1 - omit version 2.9.7
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.9.1 - omit version 2.9.7
Sending Logstash's logs to  which is now configured via log4j2.properties

An error occurred while loading ./spec/inputs/s3sqs_spec.rb.
Failure/Error: public :process_local_log # use method without error logging for better visibility of errors

NameError:
  undefined method `process_local_log' for class `LogStash::Inputs::S3SNSSQS'
# ./spec/inputs/s3sqs_spec.rb:18:in `<class:S3SNSSQS>'
# ./spec/inputs/s3sqs_spec.rb:17:in `block in <main>'
# ./spec/inputs/s3sqs_spec.rb:16:in `<main>'
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

All examples were filtered out

Randomized with seed 15020


Finished in 0.00498 seconds (files took 8.85 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 15020
```

**Comment by christianherweg0807** [comment]
What should I say...I refactored the code, but ignored the tests...

there is room for improvement ;-)

Christian

**Comment by zeph** [comment]
xD :+1:
