### ISSUE TITLE
`max_processing_time` applied to worker not a message

### ISSUE THREAD

**Issue by widgetpl** [cherweg/logstash-input-s3-sns-sqs#84]
I suppose that `max_processing_time` is applied to a worker level instead of each message consumed.
When we [`run()`](https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/master/lib/logstash/inputs/sqs/poller.rb#L69) we are setting below parameters:
```
    message_backoff = (@options[:visibility_timeout] * 95).to_f / 100.0
    new_visibility = 2 * @options[:visibility_timeout]
```
which are used to extend msg visibility by in my opinion based on logs from my logstash instance:
```
[2023-08-22T11:40:20,002][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1135Z_d7117f1f.log.gz] Extended visibility for a long running message {:visibility=>6168.0}
[2023-08-22T11:42:14,035][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1135Z_d7117f1f.log.gz] Extended visibility for a long running message {:visibility=>6282.0}
[2023-08-22T11:52:06,438][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1145Z_99c4320d.log.gz] Extended visibility for a long running message {:visibility=>6396.0}
[2023-08-22T11:54:00,481][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1145Z_99c4320d.log.gz] Extended visibility for a long running message {:visibility=>6510.0}
[2023-08-22T12:14:06,168][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1210Z_14b023e1.log.gz] Extended visibility for a long running message {:visibility=>6624.0}
[2023-08-22T12:16:00,204][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1210Z_14b023e1.log.gz] Extended visibility for a long running message {:visibility=>6738.0}
[2023-08-22T12:19:03,907][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1215Z_d1cd1468.log.gz] Extended visibility for a long running message {:visibility=>6852.0}
[2023-08-22T12:20:57,957][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1215Z_d1cd1468.log.gz] Extended visibility for a long running message {:visibility=>6966.0}
[2023-08-22T12:22:51,981][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1215Z_d1cd1468.log.gz] Extended visibility for a long running message {:visibility=>7080.0}
[2023-08-22T12:25:38,320][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1220Z_a4b41e8e.log.gz] Extended visibility for a long running message {:visibility=>7194.0}
[2023-08-22T12:32:03,297][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1225Z_ed01da21.log.gz] Extended visibility for a long running message {:visibility=>7308.0}
[2023-08-22T12:33:57,329][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1225Z_ed01da21.log.gz] Extended visibility for a long running message {:visibility=>7422.0}
[2023-08-22T12:52:05,241][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/elasticloadbalancing/eu-central-1/2023/08/22/624626636471_elasticloadbalancing_eu-central-1_app.k8s-external-79b8e5b92e.d028910f9e3732e4_20230822T1250Z_10.81.111.96_1bju7y6x.log.gz] Extended visibility for a long running message {:visibility=>7536.0}
[2023-08-22T12:55:40,520][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1245Z_a0af28eb.log.gz] Extended visibility for a long running message {:visibility=>7650.0}
[2023-08-22T13:00:17,791][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1255Z_f2b2bdf1.log.gz] Extended visibility for a long running message {:visibility=>7764.0}
[2023-08-22T13:02:11,846][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1255Z_f2b2bdf1.log.gz] Extended visibility for a long running message {:visibility=>7878.0}
[2023-08-22T13:04:05,891][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1255Z_f2b2bdf1.log.gz] Extended visibility for a long running message {:visibility=>7992.0}
[2023-08-22T13:04:05,895][ERROR][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0/extender/AWSLogs/xxxxxxxxxxxx/vpcflowlogs/eu-central-1/2023/08/22/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1255Z_f2b2bdf1.log.gz] Maximum visibility reached! We will delete this message from queue!
[2023-08-22T13:04:05,940][WARN ][logstash.inputs.s3snssqs ] [Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0] Incomplete message in read_file. We´ll throw skip_delete. {:filename=>"/tmp/tmplogstash20230821-1-angqur/624626636471_vpcflowlogs_eu-central-1_fl-0472c82cd38b8065b_20230822T1255Z_f2b2bdf1.log.gz"}
warning: thread "Worker 929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d/0" terminated with exception (report_on_exception is true):
ThreadError: killed thread
```
and then logstash restarts with below stack trace:
```
ThreadError: killed thread
             wakeup at org/jruby/RubyThread.java:1278
                run at org/jruby/RubyThread.java:1436
                run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:131
     yield_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413
               each at org/jruby/RubyArray.java:1821
     yield_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412
   process_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405
              catch at org/jruby/RubyKernel.java:1189
   process_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404
               poll at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336
               loop at org/jruby/RubyKernel.java:1442
               poll at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331
              catch at org/jruby/RubyKernel.java:1189
               poll at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330
                run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:89
   run_with_backoff at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:184
                run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:87
  run_worker_thread at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/s3snssqs.rb:336
warning: thread "Ruby-0-Thread-20: /usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:410" terminated with exception (report_on_exception is true):
ThreadError: killed thread
             wakeup at org/jruby/RubyThread.java:1278
                run at org/jruby/RubyThread.java:1436
                run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:131
     yield_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413
               each at org/jruby/RubyArray.java:1821
     yield_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412
   process_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405
              catch at org/jruby/RubyKernel.java:1189
   process_messages at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404
               poll at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336
               loop at org/jruby/RubyKernel.java:1442
               poll at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331
              catch at org/jruby/RubyKernel.java:1189
               poll at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330
                run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:89
   run_with_backoff at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:184
                run at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:87
  run_worker_thread at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/s3snssqs.rb:336
[2023-08-24T10:18:45,306][ERROR][logstash.javapipeline    ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:logstash
  Plugin: <LogStash::Inputs::S3SNSSQS codec=><LogStash::Codecs::Multiline pattern=>"^%{TIMESTAMP_ISO8601}|^\\d+%{SPACE}(\\d+|unknown)%{SPACE}eni\\-|^%{NOTSPACE}?%{SPACE}%{TIMESTAMP_ISO8601}|^[\\d/]+%{SPACE}[\\d:]+%{SPACE}|^\\d+-[A-Za-z]+-\\d+%{SPACE}[\\d:.]+%{SPACE}|^version%{SPACE}account\\-id|^{", what=>"previous", id=>"5b859b32-a9da-43ec-858c-6b8203fe463c", negate=>true, enable_metric=>true, charset=>"UTF-8", multiline_tag=>"multiline", max_lines=>500, max_bytes=>10485760>, id=>"929661514b3e74ab5d31b9d671ef356a976329f825b41c565bccbf5bbd97015d", region=>"eu-central-1", from_sns=>false, queue=>"george-at-prod-centralized-logs", tags=>["s3-centralized-logs"], enable_metric=>true, threads=>1, role_session_name=>"logstash", s3_role_session_name=>"logstash", delete_on_success=>false, include_object_properties=>[:last_modified, :content_type, :metadata], sqs_skip_delete=>false, sqs_delete_on_failure=>true, visibility_timeout=>120, max_processing_time=>8000, temporary_directory=>"/tmp/logstash", consumer_threads=>1>
  Error: killed thread
  Exception: ThreadError
  Stack: org/jruby/RubyThread.java:1278:in `wakeup'
org/jruby/RubyThread.java:1436:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:131:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413:in `block in yield_messages'
org/jruby/RubyArray.java:1821:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `yield_messages'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `block in process_messages'
org/jruby/RubyKernel.java:1189:in `catch'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `block in poll'
org/jruby/RubyKernel.java:1442:in `loop'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'
org/jruby/RubyKernel.java:1189:in `catch'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:89:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:184:in `run_with_backoff'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:87:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/s3snssqs.rb:336:in `block in run_worker_thread'
[2023-08-24T10:18:45,399][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ThreadError: killed thread>, :backtrace=>["org/jruby/RubyThread.java:1278:in `wakeup'", "org/jruby/RubyThread.java:1436:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:131:in `block in run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:413:in `block in yield_messages'", "org/jruby/RubyArray.java:1821:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:412:in `yield_messages'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `block in process_messages'", "org/jruby/RubyKernel.java:1189:in `catch'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `block in poll'", "org/jruby/RubyKernel.java:1442:in `loop'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `block in poll'", "org/jruby/RubyKernel.java:1189:in `catch'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/aws-sdk-resources-2.11.632/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:89:in `block in run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:184:in `run_with_backoff'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/sqs/poller.rb:87:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-s3-sns-sqs-2.1.3/lib/logstash/inputs/s3snssqs.rb:336:in `block in run_worker_thread'"]}
[2023-08-24T10:18:45,418][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.20.1.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.20.1.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]
```
as you can see in logs where we are extending visibility timeout we process different log files but visibility isn't restarted. 
I would suppose that we should reset `new_visibility` to starting value new_visibility = 2 * @options[:visibility_timeout] while we consume new msg/file. Even if I will set `visibility_timeout` to some higher value other then default (120 set in [code](https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/master/lib/logstash/inputs/s3snssqs.rb#L178) but [docs](https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/master/docs/index.asciidoc?plain=1#L235) says it's 5min) there still can me msgs that will take more time than let's say 5min and we will still be increasing `new_visibility` that will reach in some time `max_processing_time` and we will again fail with above error.

**Comment by a7acd8bf-359c-4d70-a42f-eb861a0cc478** [comment]
Hello @widgetpl , did you manage to resolve this issue? I'm encountering the same error.
