### ISSUE TITLE
Logstash hangs and stop processing data when having issues with Proxy

### ISSUE THREAD

**Issue by ofirEdi** [cherweg/logstash-input-s3-sns-sqs#88]
Hi,
We are using Logstash 8.11.4 with version 2.2.2 of this plugin behind a company proxy (proxy is with http and no auth) like the following:

```conf
input {
  s3snssqs {
      region => "{region}"
      s3_default_options => { "endpoint_discovery" => true }
      queue => "{queue_name}"
      queue_owner_aws_account_id => "{account id}"
      sqs_skip_delete => false
      visibility_timeout => 600
      from_sns => true
      proxy_uri => "http://{proxy address}:8080"
      aws_credentials_file => "/etc/logstash/certs/aws.yml"
      threads => 15
  }
}
```

We have multiple pipelines with similar configuration and in general they run well and able to process data.
every now and then we are getting error regarding networking issue with the proxy (it can be timeout, connection refused and even unknown host - which are probably related to our infrastructure). Afterwards, Logstash is not able to recover and we have to manually restart it (all other pipelines even not related to this plugin stops working and port 9600 becomes inaccessible):

```
[ERROR][logstash.javapipeline    ][xxxxxx][37ff69d34bb2586adb720166fcbfd63d3c66e0789bb1132928343d2cc0bd6365] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:xxxxxx
  Plugin: <LogStash::Inputs::S3SNSSQS aws_credentials_file=>"/etc/logstash/certs/aws.yml", s3_default_options=>{"endpoint_discovery"=>"true"}, visibility_timeout=>600, from_sns=>true, queue_owner_aws_account_id=>"xxxxxxxxx", sqs_skip_delete=>false, threads=>15, id=>"37ff69d34bb2586adb720166fcbfd63d3c66e0789bb1132928343d2cc0bd6365", region=>"xxxx", queue=>"xxxxxxx", proxy_uri=>"http://xxxxxxx:8080", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_b754ab35-0649-4d73-934d-c20cc0ad8cfc", enable_metric=>true, charset=>"UTF-8">, role_session_name=>"logstash", use_aws_bundled_ca=>false, s3_role_session_name=>"logstash", delete_on_success=>false, include_object_properties=>[:last_modified, :content_type, :metadata], sqs_delete_on_failure=>true, max_processing_time=>8000, temporary_directory=>"/tmp/logstash", consumer_threads=>1>
  Error: Net::OpenTimeout
  Exception: Seahorse::Client::NetworkingError
  Stack: /usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:43:in `ssl_socket_connect'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:1089:in `connect'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:995:in `do_start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:990:in `start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/delegate.rb:87:in `method_missing'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/connection_pool.rb:307:in `start_session'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/connection_pool.rb:100:in `session_for'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/handler.rb:128:in `session'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/handler.rb:50:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/content_length.rb:24:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/request_callback.rb:118:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/json/error_handler.rb:10:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/sign.rb:54:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/user_agent.rb:37:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/http_checksum.rb:20:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:137:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/request_compression.rb:94:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/plugins/queue_urls.rb:15:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/json/handler.rb:13:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/plugins/endpoints.rb:42:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/endpoint_discovery.rb:84:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/response_target.rb:24:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/request.rb:72:in `send_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/client.rb:2011:in `receive_message'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:416:in `send_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:409:in `get_messages'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:357:in `block in poll'
org/jruby/RubyKernel.java:1603:in `loop'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:356:in `block in poll'
org/jruby/RubyKernel.java:1310:in `catch'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:355:in `poll'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/sqs/poller.rb:89:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/sqs/poller.rb:184:in `run_with_backoff'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/sqs/poller.rb:87:in `run'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/s3snssqs.rb:337:in `block in run_worker_thread'
```

After this message (which appears for all s3-sns-sqs pipelines we are keep getting the below message until we restart the service and things return to normal - at that time Elasticsearch is available and other client are able to interact with it):
```
[ERROR][logstash.outputs.elasticsearch][xxxx][xxxx] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [https://xxxxx:9200/_bulk?filter_path=errors,items.*.error,items.*.status][Manticore::SocketException] Socket closed", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>2}
```

Appreciate if you can assist,
Ofir

**Comment by ofirEdi** [comment]
Another issue from today with NetworkError

```
[2024-04-15T08:06:01,826][ERROR][logstash.javapipeline    ][xxxxxx][5ac0fdf6c59b5aa3ed452d605e19cc7de030d1bc898068f46b28289e17708c66] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:xxxxxxxxxx
  Plugin: <LogStash::Inputs::S3SNSSQS aws_credentials_file=>"/etc/logstash/certs/aws.yml", s3_default_options=>{"endpoint_discovery"=>"true"}, visibility_timeout=>600, from_sns=>true, queue_owner_aws_account_id=>"xxxxxxxx", sqs_skip_delete=>false, threads=>5, id=>"5ac0fdf6c59b5aa3ed452d605e19cc7de030d1bc898068f46b28289e17708c66", region=>"xxxxx", queue=>"xxxxxxx", proxy_uri=>"http://xxxxxx:8080", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_18805572-31af-4ddb-bc3d-c192c004c65d", enable_metric=>true, charset=>"UTF-8">, role_session_name=>"logstash", use_aws_bundled_ca=>false, s3_role_session_name=>"logstash", delete_on_success=>false, include_object_properties=>[:last_modified, :content_type, :metadata], sqs_delete_on_failure=>true, max_processing_time=>8000, temporary_directory=>"/tmp/logstash", consumer_threads=>1>
  Error: closed stream
  Exception: Seahorse::Client::NetworkingError
  Stack: org/jruby/ext/io/wait/IOWaitLibrary.java:107:in `wait_readable'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:47:in `ssl_socket_connect'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:1089:in `connect'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:995:in `do_start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/net/http.rb:990:in `start'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/delegate.rb:87:in `method_missing'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/connection_pool.rb:307:in `start_session'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/connection_pool.rb:100:in `session_for'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/handler.rb:128:in `session'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/handler.rb:76:in `transmit'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/net_http/handler.rb:50:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/content_length.rb:24:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/request_callback.rb:118:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/json/error_handler.rb:10:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/sign.rb:54:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/transfer_encoding.rb:26:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:12:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:360:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:394:in `retry_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:382:in `retry_if_possible'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/retry_errors.rb:371:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/user_agent.rb:37:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/http_checksum.rb:20:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/endpoint_pattern.rb:30:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:137:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/request_compression.rb:94:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/plugins/queue_urls.rb:15:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/json/handler.rb:13:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/recursion_detection.rb:18:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/plugins/endpoints.rb:42:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/endpoint_discovery.rb:84:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/endpoint.rb:47:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/param_validator.rb:26:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/plugins/response_target.rb:24:in `call'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-core-3.190.2/lib/seahorse/client/request.rb:72:in `send_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/client.rb:2011:in `receive_message'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:416:in `send_request'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:409:in `get_messages'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:357:in `block in poll'
org/jruby/RubyKernel.java:1603:in `loop'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:356:in `block in poll'
org/jruby/RubyKernel.java:1310:in `catch'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/aws-sdk-sqs-1.69.0/lib/aws-sdk-sqs/queue_poller.rb:355:in `poll'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/sqs/poller.rb:89:in `block in run'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/sqs/poller.rb:184:in `run_with_backoff'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/sqs/poller.rb:87:in `run'
/usr/share/logstash/vendor/bundle/jruby/3.1.0/gems/logstash-input-s3-sns-sqs-2.2.2/lib/logstash/inputs/s3snssqs.rb:337:in `block in run_worker_thread'
```

**Comment by ofirEdi** [comment]
Hi,
This is still relevant and I would appreciate if this can be checked.

Thanks,
Ofir

**Comment by christianherweg0807** [comment]
Sorry for the long delay. 
In all my testing environments I can´t reproduce this problem. But I think the error handling in the poller loop could be improved a little bit.
I´ll release a pre version for testing.

**Comment by christianherweg0807** [comment]
Normally the elastic output should handle connection problems. like this:
[2024-12-10T11:07:02,418][ERROR][logstash.outputs.elasticsearch][xxx][xxx] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [https://xxx:9243/_bulk?filter_path=errors,items.*.error,items.*.status][Manticore::SocketException] No route to host", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>2}

**Comment by christianherweg0807** [comment]
You may use 
`./bin/logstash-plugin install --version 2.2.3.pre logstash-input-s3-sns-sqs`
to test.

**Comment by ofirEdi** [comment]
Thanks for the update @christianherweg0807 !
I will give it a try and will update.

**Comment by ofirEdi** [comment]
> Normally the elastic output should handle connection problems. like this: [2024-12-10T11:07:02,418][ERROR][logstash.outputs.elasticsearch][xxx][xxx] Attempted to send a bulk request but Elasticsearch appears to be unreachable or down {:message=>"Elasticsearch Unreachable: [https://xxx:9243/_bulk?filter_path=errors,items._.error,items._.status][Manticore::SocketException] No route to host", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :will_retry_in_seconds=>2}

I agree but seems that after getting `A plugin had an unrecoverable error. Will restart this plugin` Logstash is not able to restart the plugins and all existing pipelines fail with `Elasticsearch appears to be unreachable or down ` (manual restart to Logstash solves the issue).
